# Custom Language File for Launcher Customizer

[ejs.app]
title = "Epoch Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/EpochCraft/EpochLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/JFtd99FczS"

[ejs.settings]
sourceGithubLink = "https://github.com/EpochCraft/EpochLauncher"
supportLink = "https://github.com/EpochCraft/EpochLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO EPOCHCRAFT"
welcomeDescription = "We started with a GT:NH server and it blew up. Now we are expanding to other modpacks and games. See you in the game!"
welcomeDescCTA = "You are just a few clicks away from Epoch."
